version: 0.2
phases:
  pre_build:
    commands:
      - pwd
      - echo Logging in to Amazon ECR...
      - ECR_LOGIN_URL=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - ECR_REPOSITORY_URI=$ECR_LOGIN_URL/$PROJECT_NAME
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_LOGIN_URL
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo Build started on `date`
      - docker build --no-cache -t $ECR_REPOSITORY_URI:$COMMIT_HASH -t $ECR_REPOSITORY_URI:latest .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $ECR_REPOSITORY_URI:$COMMIT_HASH
      - docker push $ECR_REPOSITORY_URI:latest
      - printf '[{"name":"%s","imageUri":"%s"}]' $PROJECT_NAME $ECR_REPOSITORY_URI:$COMMIT_HASH > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
  discard-paths: yes
